### PR TITLE
drop VOS support

### PR DESCRIPTION
**Pull request by mostynb**
I strongly suspect that this is untested/unused.

### CODE REVIEW

**Comment by shawnl** [comment]
I ported distcc to meson build system, which would mean dropping old platforms like this. The problem is that there are few programmers working on distcc. To review patches and the like.

**Comment by thedrow** [comment]
I have no idea what VOS actually is.

**Comment by shawnl** [comment]
It is an operating system.

**Comment by thedrow** [comment]
According to wikipedia it is still active. Worth dropping support if there's any benefit to it.
@shawnl How does the code bother you?

**Comment by shawnl** [comment]
Not my bug just answering the question. Doesn't bother me.

**Comment by shawnl** [comment]
no need to remove this

**Pull request closed without merging**
