### PR TITLE
flag to allow -spec arguments

### PR DESCRIPTION
**Pull request by digitalist**
https://github.com/distcc/distcc/issues/253

I moved logic responsible for checking possible flags from distcc_check_args to new function: check_army_of_clones, there is only one (spec) working flag for now, but if someone will want to add additional exlcusions, it's better to have relevant code in one place

This function gets envvar DISTCC_AOC as a list of exclusions (delimited with ,), and allows to distribute payload if it
finds relevant exclusion in that var

ie: this will result in distributed build
export DISTCC_AOC="spec" ./distcc c++ helloworld.cpp -specs=123

this will result in 'must be local' message in logs
export DISTCC_AOC="" ./distcc c++ helloworld.cpp -specs=123

### CODE REVIEW

**Comment by shawnl** [comment]
I feel the real solution is to change the protocol (put this in protocol very. 4 that is in development) and ship the spec file over the wire. Thoughts?

You can fix the build by rebasing with master.

**Comment by afbjorklund** [comment]
What's with the "army of clones" thing ? Cutesy ?

**Comment by digitalist** [comment]
@shawnl I guess it depends on a speed with which v4 is developed? If it's a year, I'd vote for including this patch, if it's half a year - we should throw it away:)

@afbjorklund something like this, yes.Sounds better then 'identical_set_of_building_hosts'

**Comment by shawnl** [comment]
The problem with allowing specs files is that we don't have a sanitizer for them, for at least -fplugin=. see https://github.com/distcc/distcc/pull/276 and https://youtu.be/bSkpMdDe4g4?t=53m12s

**Comment by digitalist** [comment]
well, this option is definitely meant for trusted env, trusted source and manual enabling. Maybe we should add an option to disable some risky variants, but idk if it will ever be enough to compile random code on untrusted machines

**Pull request closed without merging**
