### PR TITLE
Enabled ccache so that the builds would run faster.

### PR DESCRIPTION
**Pull request by thedrow**

### CODE REVIEW

**Comment by thedrow** [comment]
The next build should finish faster (on Linux)...

**Comment by shawnl** [comment]
IMHO the builds happen fast enough

**Comment by thinrope** [comment]
Did it help and by how much?
Looking at https://travis-ci.org/distcc/distcc/builds there is no siginificant change...
I guess the cache (of ccache) is dropped with each build, so unless we have multiple builds (e.g. with different compile options) in a single travis build, it makes no sense.
Just my thoughts, might be completely wrong :-|

**Comment by thedrow** [comment]
@thinrope Since there is no other commit in this PR there's no way to measure. The first time the build runs populates the cache. After that the cache will be reused.

**Pull request merged**
